---
apiVersion: v1
kind: Pod
metadata:
  name: pod-1
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 55785


---
kind: Service 
apiVersion: v1 
metadata:
  name: hostname-service 
spec:
  selector:
    app.kubernetes.io/name: app-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80