apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    app.kubernetes.io/name: proxy
spec:
  containers:
    - name: nginx
      image: 581798224530.dkr.ecr.us-east-1.amazonaws.com/nginx_practise
      ports:
      - containerPort: 80



---
kind: Service 
apiVersion: v1 
metadata:
  name: pod-1
spec:
  selector:
    app.kubernetes.io/name: proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80