---
apiVersion: v1
kind: Pod
metadata:
  name: pod-1
spec:
  containers:
    - name: nginx
      image: nginx



---
kind: Service 
apiVersion: v1 
metadata:
  name: pod-1
spec:
  selector:
    app.kubernetes.io/name: app-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80