---
apiVersion: v1
kind: Pod
metadata:
  name: pod-1
spec:
  containers:
    - name: nginx
      image: 581798224530.dkr.ecr.us-east-1.amazonaws.com/nginx_practise



---
kind: Service 
apiVersion: v1 
metadata:
  name: pod-1
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: app-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80